excluded:
    - Carthage
    - Pods
    
disabled_rules:
    - function_body_length
    - identifier_name
    
identifier_name:
    max_length:
        warning: 45
        error: 60
    min_length:
        warning: 1
